name: Build Mod

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip mod folder
        run: |
          cd src
          zip -r ../WealthisHealth.zip WealthisHealth

      - name: GitHub Release and ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: WealthisHealth.zip
          generate_release_notes: true
